// src/app/portfolio/[slug]/page.tsx
"use client";

import React, { useEffect, useState } from "react";
import { Template, Title } from "@/components";
import { portfolios, technologies } from "@/data";
import { FaChevronLeft, FaLock } from "react-icons/fa";
import { useRouter } from "next/navigation";
import Lightbox from "yet-another-react-lightbox";
import Captions from "yet-another-react-lightbox/plugins/captions";
import PhotoAlbum from "react-photo-album";
import "yet-another-react-lightbox/styles.css";
import "yet-another-react-lightbox/plugins/captions.css";
import { calculateImageHeight } from "@/helpers";
import Image from "next/image";

type PortfolioDetailType = {
  params: {
    slug: string;
  };
};

type ImageType = Array<{
  src: string;
  description?: string;
  height: number;
  width: number;
}>;

const PortfolioDetail = ({ params: { slug } }: PortfolioDetailType) => {
  const portfolio: any = portfolios.find((item) => item.slug === slug);

  const [isOpen, setIsOpen] = useState<boolean>(false);
  const [imageIndex, setImageIndex] = useState<number>(0);
  const [images, setImages] = useState<ImageType>([]);

  useEffect(() => {
    (async () => {
      const temp: any = await Promise.all<any>(
        portfolio?.images.map(async (item: any) => {
          const dimension = await calculateImageHeight(item.image);

          return {
            src: item.image,
            description: item.caption,
            height: dimension.height,
            width: dimension.width,
          };
        })
      );

      setImages(temp);
    })();
  }, []);

  const router = useRouter();

  return (
    <>
      <Template menu="/portfolio">
        <a
          href="#"
          className="flex items-center space-x-2"
          onClick={() => router.back()}
        >
          <FaChevronLeft />
          <span>Back</span>
        </a>
        <Title>{portfolio.name}</Title>
        <PhotoAlbum
          layout="rows"
          targetRowHeight={400}
          photos={images}
          onClick={({ index }: { index: number }) => {
            setImageIndex(index);
            setIsOpen(true);
          }}
        />
        <p className="my-10 text-justify">
          {portfolio?.description ?? "No Description"}
        </p>
        <div className="space-x-2 mb-10">
          {portfolio?.platform.map((platform: string, index: number) => (
            <span
              key={`portfolio_platform_${index}`}
              className="bg-slate-200 px-3 text-slate-500 py-1 rounded-full font-bold"
            >
              {platform}
            </span>
          ))}
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-3 lg:divide-x mt-5 mb-10">
          <div className="py-3 lg:px-5">
            <p className="font-bold">Access:</p>
            {portfolio?.access?.is_public == 1 ? (
              portfolio.access.links.map(
                (link: { url: string; label: string }, index: number) => (
                  <a
                    key={`access_link_${index}`}
                    href={link.url}
                    className="text-sky-500 underline italic block"
                  >
                    {link.label}
                  </a>
                )
              )
            ) : (
              <span className="flex items-center gap-x-2 italic">
                <FaLock className="text-slate-300" />
                Private Access
              </span>
            )}
          </div>
          <div className="py-3 lg:px-5">
            <p className="font-bold">Role:</p>
            <p>{portfolio?.role}</p>
          </div>
          <div className="py-3 lg:px-5">
            <p className="font-bold">Technology:</p>
            <div className="grid grid-cols-3 gap-3 mt-5">
              {portfolio?.tech_stack.map(
                (tech_stack: string, index: number) => {
                  const technology = technologies.find(
                    (item) => item.code === tech_stack
                  );
                  if (!technology) return null;

                  return (
                    <div
                      className="space-y-2"
                      key={`portfolio_technology_${index}`}
                    >
                      <div className="w-full h-6 relative overflow-hidden">
                        <Image
                          className="object-contain"
                          src={technology.logo_path}
                          fill
                          quality={80}
                          loading="lazy"
                          alt={`Tech stack ${technology.name}`}
                          content="fill"
                        />
                      </div>
                      <div className="text-sm text-slate-500 text-center">
                        {technology.name}
                      </div>
                    </div>
                  );
                }
              )}
            </div>
          </div>
        </div>
        <div className="text-center space-y-1 border-t pt-4 w-full">
          <p className="font-bold uppercase text-bold text-slate-500">
            Disclaimer:
          </p>
          <p className="text-slate-500">
            Some access link may be broken due to each business process
          </p>
        </div>
      </Template>
      <Lightbox
        index={imageIndex}
        plugins={[Captions]}
        open={isOpen}
        close={() => setIsOpen(false)}
        slides={images}
      />
    </>
  );
};

export default PortfolioDetail;

// src/routes/portfolio/[slug]/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { page } from '$app/state';
	import Template from '$lib/components/Template.svelte';
	import Title from '$lib/components/Title.svelte';
	import PhotoGallery from '$lib/components/PhotoGallery.svelte';
	import Lightbox from '$lib/components/Lightbox.svelte';
	import { portfolios, technologies, profile } from '$lib/data';
	import { ChevronLeft, Lock } from '@lucide/svelte';

	const slug = $derived(page.params.slug);
	const portfolio = $derived(portfolios.find((item) => item.slug === slug));

	let isOpen = $state(false);
	let imageIndex = $state(0);

	function handleImageClick(index: number) {
		imageIndex = index;
		isOpen = true;
	}

	$effect(() => {
		if (!portfolio) {
			goto('/portfolio');
		}
	});
</script>

<svelte:head>
	{#if portfolio}
		<title>{portfolio.name} — Portfolio | {profile.name}</title>
		<meta name="description" content={portfolio.short_description} />
	{/if}
</svelte:head>

{#if portfolio}
	<Template>
		<button
			type="button"
			class="mb-4 flex items-center gap-2 font-mono text-sm text-text-secondary transition-colors hover:text-accent"
			onclick={() => history.back()}
		>
			<ChevronLeft size={16} />
			Back
		</button>

		{#if portfolio.images.length > 0}
			<div class="mb-8 overflow-hidden rounded-lg border border-border">
				<img
					src={portfolio.images[0].image}
					alt={portfolio.name}
					class="h-auto w-full object-cover"
				/>
			</div>
		{/if}

		<Title>{portfolio.name}</Title>

		<div class="mb-6 flex flex-wrap gap-2">
			{#each portfolio.platform as platform}
				<span class="rounded border border-border bg-surface px-2.5 py-1 font-mono text-xs text-text-secondary">
					{platform}
				</span>
			{/each}
		</div>

		<p class="mb-8 text-sm leading-relaxed text-text-secondary">{portfolio.description ?? 'No Description'}</p>

		<div class="grid grid-cols-1 gap-6 border-t border-border pt-6 sm:grid-cols-3">
			<div>
				<p class="mb-2 font-mono text-xs text-text-tertiary">Access</p>
				{#if portfolio.access?.is_public}
					{#each portfolio.access.links as link}
						<a href={link.url} class="block text-sm text-accent underline underline-offset-2">
							{link.label}
						</a>
					{/each}
				{:else}
					<span class="flex items-center gap-2 text-sm text-text-tertiary">
						<Lock size={14} />
						Private Access
					</span>
				{/if}
			</div>
			<div>
				<p class="mb-2 font-mono text-xs text-text-tertiary">Role</p>
				<p class="text-sm text-text-primary">{portfolio.role}</p>
			</div>
			<div>
				<p class="mb-2 font-mono text-xs text-text-tertiary">Technology</p>
				<div class="flex flex-wrap gap-2">
					{#each portfolio.tech_stack as tech_code}
						{@const technology = technologies.find((t) => t.code === tech_code)}
						{#if technology}
							<div class="flex items-center gap-1.5 rounded border border-border bg-surface px-2 py-1">
								<img
									src={technology.logo_path}
									alt={technology.name}
									class="h-4 w-4 object-contain"
									loading="lazy"
								/>
								<span class="text-xs text-text-secondary">{technology.name}</span>
							</div>
						{/if}
					{/each}
				</div>
			</div>
		</div>

		{#if portfolio.images.length > 1}
			<Title>Screenshots</Title>
			<PhotoGallery images={portfolio.images} onImageClick={handleImageClick} />
		{/if}

		<div class="mt-10 border-t border-border pt-4 text-center">
			<p class="font-mono text-xs text-text-tertiary">
				Some access links may be broken due to each business process.
			</p>
		</div>
	</Template>

	<Lightbox images={portfolio.images} currentIndex={imageIndex} open={isOpen} onClose={() => (isOpen = false)} />
{/if}
