// legacy/src/app/profile/page.tsx
import { educations, profile } from "@/data";
import dayjs from "dayjs";
import advancedFormat from "dayjs/plugin/advancedFormat";
import { Education, PageTransition, Template, Title } from "@/components";

dayjs.extend(advancedFormat);

const aboutMeLists: Array<{ label: string; value: string }> = [
  {
    label: "Name",
    value: profile.name_with_title,
  },
  {
    label: "Date of Birth",
    value: dayjs(profile.date_of_birth).format("MMMM, Do YYYY"),
  },
  {
    label: "Phone",
    value: profile.phone,
  },
  {
    label: "Email",
    value: profile.email,
  },
  {
    label: "Web",
    value: profile.website,
  },
  {
    label: "Address",
    value: profile.address?.city,
  },
];

export default function ProfilePage() {
  return (
    <Template menu="/profile">
      <PageTransition>
        <Title>About Me</Title>
        <table className="table-fixed mt-5 mx-auto">
          <tbody>
            {aboutMeLists.map((list, index) => (
              <tr key={`list_${index}`}>
                <td className="text-left text-sm w-[180px]">{list.label}</td>
                <td className="text-right font-semibold">{list.value}</td>
              </tr>
            ))}
          </tbody>
        </table>
        <Title>Education</Title>
        <ol className="relative border-l space-y-10">
          {educations.map((education, index) => (
            <Education education={education} key={`education_${index}`} />
          ))}
        </ol>
        <Title>Hobbies</Title>
        <p className="text-center md:mx-20 mb-14">{profile.hobbies}</p>
      </PageTransition>
    </Template>
  );
}

// src/routes/profile/+page.svelte
<script lang="ts">
	import Template from '$lib/components/Template.svelte';
	import PageTransition from '$lib/components/PageTransition.svelte';
	import Title from '$lib/components/Title.svelte';
	import Education from '$lib/components/Education.svelte';
	import { educations, profile } from '$lib/data';
	import dayjs from 'dayjs';
	import advancedFormat from 'dayjs/plugin/advancedFormat';

	dayjs.extend(advancedFormat);

	const aboutMeLists = [
		{ label: 'Name', value: profile.name_with_title },
		{ label: 'Date of Birth', value: dayjs(profile.date_of_birth).format('MMMM, Do YYYY') },
		{ label: 'Phone', value: profile.phone },
		{ label: 'Email', value: profile.email },
		{ label: 'Web', value: profile.website },
		{ label: 'Address', value: profile.address.city }
	];
</script>

<svelte:head>
	<title>Profile | {profile.name}</title>
	<meta name="description" content={`About ${profile.name} - ${profile.role}`} />
</svelte:head>

<Template>
	<PageTransition>
		<Title>About Me</Title>
		<dl class="mx-auto max-w-md space-y-3">
			{#each aboutMeLists as list}
				<div class="flex items-baseline justify-between border-b border-border pb-2">
					<dt class="font-mono text-sm text-text-tertiary">{list.label}</dt>
					<dd class="text-sm text-text-primary">{list.value}</dd>
				</div>
			{/each}
		</dl>
		<Title>Education</Title>
		<ol class="relative border-l border-accent/30">
			{#each educations as education}
				<Education {education} />
			{/each}
		</ol>
		<Title>Hobbies</Title>
		<p class="max-w-xl text-sm leading-relaxed text-text-secondary">{profile.hobbies}</p>
	</PageTransition>
</Template>
