// src/app/portfolio/page.tsx
"use client";

import React from "react";
import { portfolios, technologies } from "@/data";
import { FiAlertCircle } from "react-icons/fi";
import { Portfolio, Template } from "@/components";
import { AnimatePresence, motion } from "framer-motion";
import { useRouter, useSearchParams } from "next/navigation";
import { cn, getUniqueValues } from "@/helpers";
import qs, { ParsedQs } from "qs";

const groupByTechnologyType = (technologies: any) => {
  return technologies
    .filter((technology: any) => technology.type !== "tools" && technology.type !== "database")
    .reduce(function (r: any, a: any) {
      r[a.type] = r[a.type] || [];
      r[a.type].push(a);
      return r;
    }, Object.create(null));
};

export default function PortfolioPage() {
  const searchParams = useSearchParams();
  const queryParams: ParsedQs = qs.parse(searchParams.toString());

  let selectedTechnologies: string[] = (queryParams.technology || []) as string[];
  let selectedPlatforms: string[] = (queryParams.platform || []) as string[];

  const filteredPortfolio = portfolios
    .filter((portfolio) => {
      // Filter by tech
      if (selectedTechnologies.length > 0) {
        return portfolio.tech_stack.some((tech_stack) => selectedTechnologies.includes(tech_stack));
      }

      return portfolio;
    })
    .filter((portfolio) => {
      // Filter by platform
      if (selectedPlatforms.length > 0) {
        return portfolio.platform.some((platform) => selectedPlatforms.includes(platform));
      }

      return portfolio;
    });

  return (
    <Template menu="/portfolio">
      <AnimatePresence mode="wait">
        <motion.div
          initial={{ y: 10, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          exit={{ y: -10, opacity: 0 }}
          transition={{ duration: 0.2 }}
          className="overflow-y-hidden w-full h-full"
        >
          <div className="lg:grid lg:grid-cols-12 gap-6 h-full">
            <div className="col-span-2 relative overflow-y-auto">
              <SidebarTechStack selectedPlatforms={selectedPlatforms} selectedTechnologies={selectedTechnologies} />
            </div>
            <div className="col-span-10 relative lg:overflow-y-auto flex flex-col">
              {filteredPortfolio.length > 0 ? (
                <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4 py-3 relative">
                  {filteredPortfolio.map((portfolio, index) => (
                    <Portfolio key={`portfolio_${index}`} portfolio={portfolio} />
                  ))}
                </div>
              ) : (
                <div className="flex items-center justify-center flex-col space-y-5 h-full">
                  <FiAlertCircle className="text-5xl text-orange-400" />
                  <div className="text-slate-400">No Projects Found</div>
                </div>
              )}
            </div>
          </div>
        </motion.div>
      </AnimatePresence>
    </Template>
  );
}

interface TParams {
  platform: string[];
  technology: string[];
}

interface TSidebarTechStack {
  selectedTechnologies: string[];
  selectedPlatforms: string[];
}

const SidebarTechStack = (props: TSidebarTechStack) => {
  const router = useRouter();

  const { selectedTechnologies, selectedPlatforms } = props;

  const handleFilter = (code: string, type: string) => {
    let params: TParams = {
      platform: selectedPlatforms,
      technology: selectedTechnologies,
    };

    let isDeleted = false;
    if (type === "platform") {
      if (params.platform.includes(code)) {
        isDeleted = true;
        params = {
          ...params,
          platform: params.platform.filter((item) => item !== code),
        };
      }
    } else {
      if (params?.technology.includes(code)) {
        isDeleted = true;
        params = {
          ...params,
          technology: params?.technology.filter((item) => item !== code),
        };
      }
    }

    if (!isDeleted) {
      if (type === "platform") {
        params = {
          ...params,
          platform: getUniqueValues([...params.platform, code]),
        };
      } else {
        params = {
          ...params,
          technology: getUniqueValues([...params.technology, code]),
        };
      }
    }

    const queryString = qs.stringify(params, { encode: false });

    router.push(`/portfolio?${queryString}`);
  };

  return (
    <div className="lg:absolute space-y-2 top-0 left-0 w-full pb-5">
      {Object.keys(groupByTechnologyType(technologies)).map((type, index) => (
        <div className="space-y-2 w-full" key={`type_${index}`}>
          <span className="block text-sm uppercase font-bold pt-5">{type}</span>
          <div className="flex flex-wrap gap-3 lg:block lg:space-y-2">
            {technologies
              .filter((technology) => technology.type === type)
              .map((technology, technology_index) => (
                <button
                  data-umami-event={`[PORTFOLIO][TECH STACK] ${technology.name}`}
                  key={`technology_${index}_${technology_index}`}
                  className={cn(
                    `block w-full text-left duration-200 hover:scale-[90%] hover:border-primary-600 hover:text-primary-600 px-2 py-1 text-sm border cursor-pointer rounded-lg pointer`,
                    selectedTechnologies.find((item) => item === technology.code)
                      ? "border-primary-600 text-primary-600"
                      : "text-slate-600",
                    selectedPlatforms.find((item) => item === technology.code)
                      ? "border-primary-600 text-primary-600"
                      : "text-slate-600"
                  )}
                  onClick={() => handleFilter(technology.code, technology.type)}
                >
                  {technology.name}
                </button>
              ))}
          </div>
        </div>
      ))}
    </div>
  );
};

// src/routes/portfolio/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { browser } from '$app/environment';
	import Template from '$lib/components/Template.svelte';
	import PageTransition from '$lib/components/PageTransition.svelte';
	import Portfolio from '$lib/components/Portfolio.svelte';
	import { portfolios, technologies, profile } from '$lib/data';
	import { cn, getUniqueValues } from '$lib/helpers';
	import { AlertCircle } from '@lucide/svelte';
	import qs from 'qs';

	const groupedTechnologies = $derived(
		technologies.reduce(
			(acc, t) => {
				acc[t.type] = acc[t.type] || [];
				acc[t.type].push(t);
				return acc;
			},
			{} as Record<string, typeof technologies>
		)
	);

	let selectedTechnologies = $state<string[]>([]);
	let selectedPlatforms = $state<string[]>([]);

	$effect(() => {
		if (browser) {
			const params = qs.parse(window.location.search.slice(1));
			selectedTechnologies = (params.technology as string[]) || [];
			selectedPlatforms = (params.platform as string[]) || [];
		}
	});

	const filteredPortfolio = $derived(
		portfolios.filter((p) => {
			if (selectedTechnologies.length > 0 && !p.tech_stack.some((t) => selectedTechnologies.includes(t))) {
				return false;
			}
			if (selectedPlatforms.length > 0 && !p.platform.some((pl) => selectedPlatforms.includes(pl))) {
				return false;
			}
			return true;
		})
	);

	function handleFilter(code: string, type: string) {
		let params: { platform: string[]; technology: string[] } = {
			platform: [...selectedPlatforms],
			technology: [...selectedTechnologies]
		};

		const targetArray = type === 'platform' ? params.platform : params.technology;
		const idx = targetArray.indexOf(code);

		if (idx >= 0) {
			targetArray.splice(idx, 1);
		} else {
			targetArray.push(code);
			if (type === 'platform') {
				params.platform = getUniqueValues(params.platform);
			} else {
				params.technology = getUniqueValues(params.technology);
			}
		}

		selectedTechnologies = params.technology;
		selectedPlatforms = params.platform;

		const queryString = qs.stringify(params, { encode: false });
		goto(`/portfolio?${queryString}`, { replaceState: true });
	}
</script>

<svelte:head>
	<title>Portfolio | {profile.name}</title>
	<meta name="description" content={`Portfolio projects by ${profile.name}`} />
</svelte:head>

<Template>
	<PageTransition>
		<div class="mb-6 flex items-start gap-3 rounded-lg border border-accent/20 bg-accent/5 p-4">
			<AlertCircle class="mt-0.5 flex-shrink-0 text-xl text-accent" />
			<div class="text-sm text-text-secondary">
				<strong class="text-text-primary">Note:</strong> The projects showcased here are freelance and personal
				projects. Work done during office hours remains proprietary to the respective companies.
			</div>
		</div>

		<div class="flex flex-col gap-6 lg:flex-row">
			<aside class="w-full shrink-0 lg:w-56">
				<div class="space-y-4">
					{#each Object.entries(groupedTechnologies) as [type, techs]}
						<div>
							<span class="mb-2 block font-mono text-xs uppercase text-text-tertiary">{type}</span>
							<div class="flex flex-wrap gap-2 lg:block lg:space-y-1.5">
								{#each techs as technology}
									{@const isSelected =
										selectedTechnologies.includes(technology.code) || selectedPlatforms.includes(technology.code)}
									<button
										data-umami-event="[PORTFOLIO][TECH STACK] {technology.name}"
										class={cn(
											'rounded border px-2.5 py-1 text-left text-xs transition-all duration-150',
											isSelected
												? 'border-accent bg-accent/10 text-accent'
												: 'border-border bg-surface text-text-secondary hover:border-border-accent hover:text-text-primary'
										)}
										onclick={() => handleFilter(technology.code, technology.type)}
									>
										{technology.name}
									</button>
								{/each}
							</div>
						</div>
					{/each}
				</div>
			</aside>

			<div class="min-w-0 flex-1">
				{#if filteredPortfolio.length > 0}
					<div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
						{#each filteredPortfolio as portfolio}
							<Portfolio {portfolio} />
						{/each}
					</div>
				{:else}
					<div class="flex h-64 flex-col items-center justify-center space-y-3">
						<AlertCircle class="text-4xl text-text-tertiary" />
						<p class="text-sm text-text-tertiary">No Projects Found</p>
					</div>
				{/if}
			</div>
		</div>
	</PageTransition>
</Template>
