// src/components/Experience.tsx
import dayjs from "dayjs";
import React from "react";
import { RxDotFilled } from "react-icons/rx";
import { MdWork } from "react-icons/md";

interface TExperience {
  experience: {
    working_date: Array<{
      start_month: number;
      start_year: number;
      end_month?: number | null;
      end_year?: number | null;
      status: string;
    }>;
    company: string;
    position: string;
    description: string;
  };
}

const Experience = (props: TExperience) => {
  const { experience } = props;

  return (
    <li className="ml-5">
      <span className="flex absolute -left-3 justify-center items-center w-6 h-6 bg-primary-200 rounded-full ring-8 ring-white">
        <MdWork className="text-primary-600 text-xs" />
      </span>
      {experience.working_date.map((working_date, index) => (
        <div
          className="text-sm font-normal space-x-2 text-gray-400 flex items-center"
          key={`working_date_${experience.company}_${index}`}
        >
          <span>
            {dayjs(
              `${working_date.start_year}-${working_date.start_month}-01`
            ).format("MMM YYYY")}
            {" - "}
            {working_date.end_month && working_date.end_year
              ? dayjs(
                  `${working_date.start_year}-${working_date.start_month}-01`
                ).format("MMM YYYY")
              : "Now"}
          </span>
          <RxDotFilled className="text-sm inline-block text-primary-600" />
          <span className="text-gray-400">{working_date.status}</span>
        </div>
      ))}
      <h3 className="flex items-center mb-1 text-lg font-semibold text-gray-900">
        {experience.company} - {experience.position}
      </h3>
      <p className="mb-4 text-sm font-normal text-gray-500">
        {experience.description}{" "}
      </p>
    </li>
  );
};

export default Experience;

// src/lib/components/Experience.svelte
<script lang="ts">
	import dayjs from 'dayjs';
	import advancedFormat from 'dayjs/plugin/advancedFormat';
	import type { IExperience } from '$lib/types';

	dayjs.extend(advancedFormat);

	let { experience }: { experience: IExperience } = $props();
</script>

<li class="ml-6 pb-8 last:pb-0">
	<span
		class="bg-surface ring-accent absolute -left-[9px] top-0 flex h-4 w-4 items-center justify-center rounded-full ring-2"
	>
		<span class="h-1.5 w-1.5 rounded-full bg-accent"></span>
	</span>
	{#each experience.working_date as working_date}
		<div class="mb-2 flex flex-wrap items-center gap-2 font-mono text-xs text-text-tertiary">
			<span class="text-accent">
				{dayjs(`${working_date.start_year}-${working_date.start_month}-01`).format('MMM YYYY')} — {working_date.end_month && working_date.end_year
					? dayjs(`${working_date.end_year}-${working_date.end_month}-01`).format('MMM YYYY')
					: 'Now'}
			</span>
			<span class="text-text-tertiary">·</span>
			<span>{working_date.status}</span>
			{#if experience.location}
				<span class="text-text-tertiary">·</span>
				<span>{experience.location}</span>
			{/if}
		</div>
	{/each}
	<h3 class="text-base font-semibold text-text-primary">{experience.company}</h3>
	<p class="mb-2 font-mono text-sm text-text-secondary">{experience.position}</p>
	<p class="text-sm leading-relaxed text-text-tertiary">{experience.description}</p>
</li>
