// src/components/Menu.tsx
import React from "react";
import Link from "next/link";
import { IMenuList } from "@/types";

const menuList: IMenuList[] = [
  {
    name: "Home",
    route: "/",
  },
  {
    name: "Profile",
    route: "/profile",
  },
  {
    name: "Resume",
    route: "/resume",
  },
  {
    name: "Portfolio",
    route: "/portfolio",
  },
];

type ActiveType = (typeof menuList)[number]["route"];

const Menu = ({ active }: { active: ActiveType }) => {
  return (
    <div className="flex lg:justify-center space-x-2 p-5 bg-gray-100 shadow-sm overflow-x-auto rounded-xl">
      {menuList.map((item, index) => (
        <Link key={`menu_${index}`} href={item.route} data-umami-event={`[MENU] ${item.name}`}>
          {active === item.route ? (
            <div className="cursor-pointer px-3 py-2 flex justify-center items-center gap-x-3 text-slate-700 text-sm lg:text-base hover:text-slate-900 border-b-2 border-b-primary-500">
              <div className="font-bold text-primary-500">{item.name}</div>
            </div>
          ) : (
            <div className="cursor-pointer px-3 py-2 flex justify-center items-center gap-x-3 text-slate-700 text-sm lg:text-base transition-transform hover:text-slate-900 hover:border-b-2 border-b-primary-500 duration-300">
              <div className="font-medium">{item.name}</div>
            </div>
          )}
        </Link>
      ))}
    </div>
  );
};

export default Menu;

// src/lib/components/Menu.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { cn } from '$lib/helpers';

	const menuList = [
		{ name: 'Home', route: '/', index: '01.' },
		{ name: 'Profile', route: '/profile', index: '02.' },
		{ name: 'Resume', route: '/resume', index: '03.' },
		{ name: 'Portfolio', route: '/portfolio', index: '04.' }
	];

	let { active }: { active?: string } = $props();

	const currentPath = $derived(page.url.pathname);
</script>

<!-- Desktop: vertical nav -->
<div class="hidden flex-col space-y-1 lg:flex">
	{#each menuList as item}
		{@const isActive = active === item.route || (item.route !== '/' && currentPath.startsWith(item.route))}
		<a
			href={item.route}
			data-umami-event="[MENU] {item.name}"
			class={cn(
				'font-mono text-sm transition-all duration-150',
				isActive
					? 'border-l-2 border-l-accent pl-3 text-accent'
					: 'pl-4 text-text-secondary hover:pl-5 hover:text-text-primary'
			)}
		>
			<span class="text-text-tertiary">{item.index}</span> {item.name}
		</a>
	{/each}
</div>

<!-- Mobile: horizontal tabs -->
<div class="flex space-x-1 overflow-x-auto lg:hidden">
	{#each menuList as item}
		{@const isActive = active === item.route || (item.route !== '/' && currentPath.startsWith(item.route))}
		<a
			href={item.route}
			data-umami-event="[MENU] {item.name}"
			class={cn(
				'whitespace-nowrap rounded px-3 py-1.5 font-mono text-xs transition-colors duration-150',
				isActive ? 'bg-accent/10 text-accent' : 'text-text-secondary hover:text-text-primary'
			)}
		>
			{item.name}
		</a>
	{/each}
</div>
